bot:
  token: MTMwNDA2MTEyNjAwNjQwNzE4OQ.Gidep1.wkd0ztQG-Uu3hIgs7KlrL1v5CZLAnf9G1-q7Aw
  owner_ids:
    - 123456789123456789
    - 987654321987654321
  prefix: $
  default_bet: 100
  bonus_multiplier: 5
  bonus_cooldown: 12
